/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize};

/// struct for typed errors of method [`gw_api_v1_enumerations_enumeration_type_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GwApiV1EnumerationsEnumerationTypeGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

pub async fn gw_api_v1_enumerations_enumeration_type_get(
    configuration: &configuration::Configuration,
    enumeration_type: &str,
    currency: Option<&str>,
    ib_entity: Option<&str>,
    md_status_non_pro: Option<&str>,
    form_number: Option<&str>,
) -> Result<serde_json::Value, Error<GwApiV1EnumerationsEnumerationTypeGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!(
        "{}/gw/api/v1/enumerations/{enumerationType}",
        local_var_configuration.base_path,
        enumerationType = crate::apis::urlencode(enumeration_type)
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = currency {
        local_var_req_builder =
            local_var_req_builder.query(&[("currency", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = ib_entity {
        local_var_req_builder =
            local_var_req_builder.query(&[("ibEntity", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = md_status_non_pro {
        local_var_req_builder =
            local_var_req_builder.query(&[("mdStatusNonPro", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = form_number {
        local_var_req_builder =
            local_var_req_builder.query(&[("form-number", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GwApiV1EnumerationsEnumerationTypeGetError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}
