/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GwApiV1ExternalAssetTransfersClientIdPostRequestInstruction {
    FopInstruction(Box<models::FopInstruction>),
    DwacInstruction(Box<models::DwacInstruction>),
    ComplexAssetTransferInstruction(Box<models::ComplexAssetTransferInstruction>),
    ExternalPositionTransfer(Box<models::ExternalPositionTransfer>),
}

impl Default for GwApiV1ExternalAssetTransfersClientIdPostRequestInstruction {
    fn default() -> Self {
        Self::FopInstruction(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "IN")]
    In,
    #[serde(rename = "OUT")]
    Out,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::In
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "FULL")]
    Full,
}

impl Default for Type {
    fn default() -> Type {
        Self::Full
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Subtype {
    #[serde(rename = "ACATS")]
    Acats,
}

impl Default for Subtype {
    fn default() -> Subtype {
        Self::Acats
    }
}

