/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GwApiV1ExternalAssetTransfersPostRequest {
    #[serde(rename = "instructionType")]
    pub instruction_type: InstructionType,
    #[serde(rename = "instruction")]
    pub instruction: Box<models::GwApiV1ExternalAssetTransfersPostRequestInstruction>,
}

impl GwApiV1ExternalAssetTransfersPostRequest {
    pub fn new(instruction_type: InstructionType, instruction: models::GwApiV1ExternalAssetTransfersPostRequestInstruction) -> GwApiV1ExternalAssetTransfersPostRequest {
        GwApiV1ExternalAssetTransfersPostRequest {
            instruction_type,
            instruction: Box::new(instruction),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InstructionType {
    #[serde(rename = "dwac")]
    Dwac,
    #[serde(rename = "fop")]
    Fop,
    #[serde(rename = "complex_asset_transfer")]
    ComplexAssetTransfer,
    #[serde(rename = "external_position_transfer")]
    ExternalPositionTransfer,
}

impl Default for InstructionType {
    fn default() -> InstructionType {
        Self::Dwac
    }
}

