/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaAllperiodsParam0PostRequest {
    /// An array of strings containing each account identifier to retrieve performance details for.
    #[serde(rename = "acctIds", skip_serializing_if = "Option::is_none")]
    pub acct_ids: Option<Vec<String>>,
}

impl PaAllperiodsParam0PostRequest {
    pub fn new() -> PaAllperiodsParam0PostRequest {
        PaAllperiodsParam0PostRequest {
            acct_ids: None,
        }
    }
}

