/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountRep {
    #[serde(rename = "repDetail", skip_serializing_if = "Option::is_none")]
    pub rep_detail: Option<Vec<models::RepDetail>>,
    #[serde(rename = "isIncluded", skip_serializing_if = "Option::is_none")]
    pub is_included: Option<bool>,
}

impl AccountRep {
    pub fn new() -> AccountRep {
        AccountRep {
            rep_detail: None,
            is_included: None,
        }
    }
}

