/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountStatusRequest {
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
}

impl AccountStatusRequest {
    pub fn new() -> AccountStatusRequest {
        AccountStatusRequest {
            start_date: None,
            end_date: None,
            offset: None,
            limit: None,
            status: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "N")]
    N,
    #[serde(rename = "O")]
    O,
    #[serde(rename = "P")]
    P,
    #[serde(rename = "C")]
    C,
    #[serde(rename = "A")]
    A,
    #[serde(rename = "E")]
    E,
    #[serde(rename = "F")]
    F,
    #[serde(rename = "I")]
    I,
    #[serde(rename = "J")]
    J,
    #[serde(rename = "L")]
    L,
    #[serde(rename = "M")]
    M,
    #[serde(rename = "R")]
    R,
    #[serde(rename = "W")]
    W,
    #[serde(rename = "Q")]
    Q,
}

impl Default for Status {
    fn default() -> Status {
        Self::N
    }
}

