/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AchInstructionClientAccountInfo {
    #[serde(rename = "bankRoutingNumber")]
    pub bank_routing_number: String,
    #[serde(rename = "bankAccountNumber")]
    pub bank_account_number: String,
    #[serde(rename = "bankName")]
    pub bank_name: String,
    #[serde(rename = "accountTypeCode", skip_serializing_if = "Option::is_none")]
    pub account_type_code: Option<f64>,
}

impl AchInstructionClientAccountInfo {
    pub fn new(bank_routing_number: String, bank_account_number: String, bank_name: String) -> AchInstructionClientAccountInfo {
        AchInstructionClientAccountInfo {
            bank_routing_number,
            bank_account_number,
            bank_name,
            account_type_code: None,
        }
    }
}

