/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddMiFirData {
    #[serde(rename = "referenceAccountId", skip_serializing_if = "Option::is_none")]
    pub reference_account_id: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "identifications", skip_serializing_if = "Option::is_none")]
    pub identifications: Option<Vec<models::Identification>>,
}

impl AddMiFirData {
    pub fn new() -> AddMiFirData {
        AddMiFirData {
            reference_account_id: None,
            title: None,
            identifications: None,
        }
    }
}

