/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddNewUser {
    #[serde(rename = "referenceAccountId", skip_serializing_if = "Option::is_none")]
    pub reference_account_id: Option<String>,
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
    #[serde(rename = "userDetails", skip_serializing_if = "Option::is_none")]
    pub user_details: Option<Box<models::UserDetails>>,
}

impl AddNewUser {
    pub fn new() -> AddNewUser {
        AddNewUser {
            reference_account_id: None,
            prefix: None,
            user_details: None,
        }
    }
}

