/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AlgoParamDefaultValue : Default parameter value. Type defined in valueClassName field
/// Default parameter value. Type defined in valueClassName field
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AlgoParamDefaultValue {
    String(String),
    Integer(i32),
    Boolean(bool),
    Number(f64),
}

impl Default for AlgoParamDefaultValue {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

