/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssociatedEntity {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Box<models::Address>>,
    #[serde(rename = "phones", skip_serializing_if = "Option::is_none")]
    pub phones: Option<Vec<models::PhoneInfo>>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "legalEntityIdentification", skip_serializing_if = "Option::is_none")]
    pub legal_entity_identification: Option<Box<models::LegalEntityIdentification>>,
    #[serde(rename = "taxResidencies", skip_serializing_if = "Option::is_none")]
    pub tax_residencies: Option<Vec<models::TaxResidency>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "externalId", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    #[serde(rename = "isUsTaxResident", skip_serializing_if = "Option::is_none")]
    pub is_us_tax_resident: Option<bool>,
    #[serde(rename = "isTranslated", skip_serializing_if = "Option::is_none")]
    pub is_translated: Option<bool>,
    #[serde(rename = "ownership", skip_serializing_if = "Option::is_none")]
    pub ownership: Option<Box<models::Ownership>>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<Box<models::Title>>,
    #[serde(rename = "associatedIndividual", skip_serializing_if = "Option::is_none")]
    pub associated_individual: Option<Box<models::AssociatedIndividual>>,
}

impl AssociatedEntity {
    pub fn new() -> AssociatedEntity {
        AssociatedEntity {
            name: None,
            location: None,
            phones: None,
            email: None,
            legal_entity_identification: None,
            tax_residencies: None,
            id: None,
            external_id: None,
            is_us_tax_resident: None,
            is_translated: None,
            ownership: None,
            title: None,
            associated_individual: None,
        }
    }
}

