/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AvailableDatesRequest {
    /// account id
    #[serde(rename = "acct")]
    pub acct: String,
    /// type of report
    #[serde(rename = "type")]
    pub r#type: String,
}

impl AvailableDatesRequest {
    pub fn new(acct: String, r#type: String) -> AvailableDatesRequest {
        AvailableDatesRequest {
            acct,
            r#type,
        }
    }
}

