/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BrokerageService {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<Code>,
}

impl BrokerageService {
    pub fn new() -> BrokerageService {
        BrokerageService { code: None }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "IBClearing")]
    IbClearing,
    #[serde(rename = "IBExecution")]
    IbExecution,
    #[serde(rename = "IBPrime")]
    IbPrime,
}

impl Default for Code {
    fn default() -> Code {
        Self::IbClearing
    }
}
