/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BusinessRejectResponse {
    #[serde(rename = "httpStatusCode")]
    pub http_status_code: i32,
    #[serde(rename = "instructionSetId")]
    pub instruction_set_id: i32,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "instructionResult", skip_serializing_if = "Option::is_none")]
    pub instruction_result: Option<Box<models::InstructionResult>>,
}

impl BusinessRejectResponse {
    pub fn new(http_status_code: i32, instruction_set_id: i32, r#type: String, title: String) -> BusinessRejectResponse {
        BusinessRejectResponse {
            http_status_code,
            instruction_set_id,
            r#type,
            title,
            instruction_result: None,
        }
    }
}

