/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeFinancialInformation {
    #[serde(rename = "referenceAccountId", skip_serializing_if = "Option::is_none")]
    pub reference_account_id: Option<String>,
    #[serde(rename = "newFinancialInformation", skip_serializing_if = "Option::is_none")]
    pub new_financial_information: Option<Box<models::FinancialInformation>>,
}

impl ChangeFinancialInformation {
    pub fn new() -> ChangeFinancialInformation {
        ChangeFinancialInformation {
            reference_account_id: None,
            new_financial_information: None,
        }
    }
}

