/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeBaseCurrency {
    #[serde(rename = "referenceAccountId", skip_serializing_if = "Option::is_none")]
    pub reference_account_id: Option<String>,
    #[serde(rename = "newBaseCurrency", skip_serializing_if = "Option::is_none")]
    pub new_base_currency: Option<String>,
}

impl ChangeBaseCurrency {
    pub fn new() -> ChangeBaseCurrency {
        ChangeBaseCurrency {
            reference_account_id: None,
            new_base_currency: None,
        }
    }
}

