/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeMarginType {
    #[serde(rename = "documentSubmission", skip_serializing_if = "Option::is_none")]
    pub document_submission: Option<Box<models::DocumentSubmission>>,
    #[serde(rename = "referenceAccountId", skip_serializing_if = "Option::is_none")]
    pub reference_account_id: Option<String>,
    #[serde(rename = "newMargin", skip_serializing_if = "Option::is_none")]
    pub new_margin: Option<String>,
}

impl ChangeMarginType {
    pub fn new() -> ChangeMarginType {
        ChangeMarginType {
            document_submission: None,
            reference_account_id: None,
            new_margin: None,
        }
    }
}

