/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComplexAssetTransferInstruction {
    #[serde(rename = "clientInstructionId")]
    pub client_instruction_id: String,
    #[serde(rename = "direction")]
    pub direction: Direction,
    #[serde(rename = "accountId")]
    pub account_id: String,
    #[serde(rename = "quantity")]
    pub quantity: f64,
    #[serde(rename = "tradingInstrument")]
    pub trading_instrument: Box<models::TradingInstrument>,
    #[serde(rename = "contraBrokerInfo")]
    pub contra_broker_info: Box<models::ContraBrokerInfo>,
    #[serde(rename = "nonDisclosedDetail", skip_serializing_if = "Option::is_none")]
    pub non_disclosed_detail: Option<Box<models::NonDisclosedDetail>>,
}

impl ComplexAssetTransferInstruction {
    pub fn new(client_instruction_id: String, direction: Direction, account_id: String, quantity: f64, trading_instrument: models::TradingInstrument, contra_broker_info: models::ContraBrokerInfo) -> ComplexAssetTransferInstruction {
        ComplexAssetTransferInstruction {
            client_instruction_id,
            direction,
            account_id,
            quantity,
            trading_instrument: Box::new(trading_instrument),
            contra_broker_info: Box::new(contra_broker_info),
            non_disclosed_detail: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "IN")]
    In,
    #[serde(rename = "OUT")]
    Out,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::In
    }
}

