/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ControllerDetailsType {
    #[serde(rename = "exchangeCode", skip_serializing_if = "Option::is_none")]
    pub exchange_code: Option<String>,
}

impl ControllerDetailsType {
    pub fn new() -> ControllerDetailsType {
        ControllerDetailsType {
            exchange_code: None,
        }
    }
}

