/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ControllingPersonType {
    #[serde(rename = "designation", skip_serializing_if = "Option::is_none")]
    pub designation: Option<Designation>,
}

impl ControllingPersonType {
    pub fn new() -> ControllingPersonType {
        ControllingPersonType {
            designation: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Designation {
    #[serde(rename = "SENIOR_MGMT_OFFICER")]
    SeniorMgmtOfficer,
    #[serde(rename = "BY_OWNERSHIP")]
    ByOwnership,
    #[serde(rename = "BY_OTHER_MEANS")]
    ByOtherMeans,
}

impl Default for Designation {
    fn default() -> Designation {
        Self::SeniorMgmtOfficer
    }
}

