/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSessionRequest {
    /// The underlying client ID
    #[serde(rename = "iss")]
    pub iss: String,
    /// A unique JWT ID used to prevent replay attacks
    #[serde(rename = "jti")]
    pub jti: String,
    #[serde(rename = "service")]
    pub service: String,
    #[serde(rename = "credential")]
    pub credential: String,
    #[serde(rename = "userIp", skip_serializing_if = "Option::is_none")]
    pub user_ip: Option<String>,
}

impl CreateSessionRequest {
    pub fn new(iss: String, jti: String, service: String, credential: String) -> CreateSessionRequest {
        CreateSessionRequest {
            iss,
            jti,
            service,
            credential,
            user_ip: None,
        }
    }
}

