/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnumerationResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::ErrorResponse>>,
    #[serde(rename = "hasError", skip_serializing_if = "Option::is_none")]
    pub has_error: Option<bool>,
    #[serde(rename = "errorDescription", skip_serializing_if = "Option::is_none")]
    pub error_description: Option<String>,
    #[serde(rename = "enumerationsType", skip_serializing_if = "Option::is_none")]
    pub enumerations_type: Option<String>,
    #[serde(rename = "jsonData", skip_serializing_if = "Option::is_none")]
    pub json_data: Option<serde_json::Value>,
}

impl EnumerationResponse {
    pub fn new() -> EnumerationResponse {
        EnumerationResponse {
            error: None,
            has_error: None,
            error_description: None,
            enumerations_type: None,
            json_data: None,
        }
    }
}

