/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileDetailsResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::ErrorResponse>>,
    #[serde(rename = "hasError", skip_serializing_if = "Option::is_none")]
    pub has_error: Option<bool>,
    #[serde(rename = "errorDescription", skip_serializing_if = "Option::is_none")]
    pub error_description: Option<String>,
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "requestFileName", skip_serializing_if = "Option::is_none")]
    pub request_file_name: Option<String>,
    #[serde(rename = "responseFileName", skip_serializing_if = "Option::is_none")]
    pub response_file_name: Option<String>,
}

impl FileDetailsResponse {
    pub fn new() -> FileDetailsResponse {
        FileDetailsResponse {
            error: None,
            has_error: None,
            error_description: None,
            account_id: None,
            request_file_name: None,
            response_file_name: None,
        }
    }
}

