/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRecentRecurringEventDetails {
    #[serde(rename = "clientInstructionId")]
    pub client_instruction_id: String,
    #[serde(rename = "ibReferenceId")]
    pub ib_reference_id: String,
    #[serde(rename = "numberOfTransactions", skip_serializing_if = "Option::is_none")]
    pub number_of_transactions: Option<f64>,
}

impl GetRecentRecurringEventDetails {
    pub fn new(client_instruction_id: String, ib_reference_id: String) -> GetRecentRecurringEventDetails {
        GetRecentRecurringEventDetails {
            client_instruction_id,
            ib_reference_id,
            number_of_transactions: None,
        }
    }
}

