/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetParticipatingListResponse {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "participatingBanks")]
    pub participating_banks: Box<models::GetParticipatingListResponseParticipatingBanks>,
}

impl GetParticipatingListResponse {
    pub fn new(r#type: String, participating_banks: models::GetParticipatingListResponseParticipatingBanks) -> GetParticipatingListResponse {
        GetParticipatingListResponse {
            r#type,
            participating_banks: Box::new(participating_banks),
        }
    }
}

