/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAvailableDatesResponse {
    /// response code
    #[serde(rename = "rc", skip_serializing_if = "Option::is_none")]
    pub rc: Option<i32>,
    /// status message
    #[serde(rename = "msg", skip_serializing_if = "Option::is_none")]
    pub msg: Option<String>,
    /// Base 64 encoded String of report data
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
    /// Type of data in property data
    #[serde(rename = "dataType", skip_serializing_if = "Option::is_none")]
    pub data_type: Option<String>,
}

impl GetAvailableDatesResponse {
    pub fn new() -> GetAvailableDatesResponse {
        GetAvailableDatesResponse {
            rc: None,
            msg: None,
            data: None,
            data_type: None,
        }
    }
}

