/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRecentInstructionsQueryTransactionHistory {
    #[serde(rename = "daysToGoBack")]
    pub days_to_go_back: f64,
    #[serde(rename = "transactionType", skip_serializing_if = "Option::is_none")]
    pub transaction_type: Option<String>,
}

impl GetRecentInstructionsQueryTransactionHistory {
    pub fn new(days_to_go_back: f64) -> GetRecentInstructionsQueryTransactionHistory {
        GetRecentInstructionsQueryTransactionHistory {
            days_to_go_back,
            transaction_type: None,
        }
    }
}

