/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFeeTemplateQuery {
    #[serde(rename = "clientInstructionId")]
    pub client_instruction_id: String,
    #[serde(rename = "accountId")]
    pub account_id: String,
    #[serde(rename = "bankInstructionMethod")]
    pub bank_instruction_method: String,
}

impl GetFeeTemplateQuery {
    pub fn new(client_instruction_id: String, account_id: String, bank_instruction_method: String) -> GetFeeTemplateQuery {
        GetFeeTemplateQuery {
            client_instruction_id,
            account_id,
            bank_instruction_method,
        }
    }
}

