/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkDuplicateAccount {
    #[serde(rename = "referenceAccountId", skip_serializing_if = "Option::is_none")]
    pub reference_account_id: Option<String>,
    #[serde(rename = "externalAccountId", skip_serializing_if = "Option::is_none")]
    pub external_account_id: Option<String>,
    #[serde(rename = "clientActiveTrading", skip_serializing_if = "Option::is_none")]
    pub client_active_trading: Option<bool>,
}

impl LinkDuplicateAccount {
    pub fn new() -> LinkDuplicateAccount {
        LinkDuplicateAccount {
            reference_account_id: None,
            external_account_id: None,
            client_active_trading: None,
        }
    }
}

