/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginMessageResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::ErrorResponse>>,
    #[serde(rename = "hasError", skip_serializing_if = "Option::is_none")]
    pub has_error: Option<bool>,
    #[serde(rename = "errorDescription", skip_serializing_if = "Option::is_none")]
    pub error_description: Option<String>,
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "clearingStatus", skip_serializing_if = "Option::is_none")]
    pub clearing_status: Option<String>,
    #[serde(rename = "clearingStatusDescription", skip_serializing_if = "Option::is_none")]
    pub clearing_status_description: Option<String>,
    #[serde(rename = "loginMessagePresent", skip_serializing_if = "Option::is_none")]
    pub login_message_present: Option<bool>,
    #[serde(rename = "loginMessages", skip_serializing_if = "Option::is_none")]
    pub login_messages: Option<Vec<models::LoginMessage>>,
}

impl LoginMessageResponse {
    pub fn new() -> LoginMessageResponse {
        LoginMessageResponse {
            error: None,
            has_error: None,
            error_description: None,
            account_id: None,
            clearing_status: None,
            clearing_status_description: None,
            login_message_present: None,
            login_messages: None,
        }
    }
}

