/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrgRegulatoryInfoType {
    #[serde(rename = "publicCompanyInfo", skip_serializing_if = "Option::is_none")]
    pub public_company_info: Option<Box<models::PublicCompanyInfoType>>,
    #[serde(rename = "orgRegulators", skip_serializing_if = "Option::is_none")]
    pub org_regulators: Option<Vec<models::OrgRegulatorType>>,
    #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<bool>,
    #[serde(rename = "isRegulated", skip_serializing_if = "Option::is_none")]
    pub is_regulated: Option<bool>,
}

impl OrgRegulatoryInfoType {
    pub fn new() -> OrgRegulatoryInfoType {
        OrgRegulatoryInfoType {
            public_company_info: None,
            org_regulators: None,
            is_public: None,
            is_regulated: None,
        }
    }
}

