/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartialCashPosition {
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f32>,
    #[serde(rename = "isMarginLoan", skip_serializing_if = "Option::is_none")]
    pub is_margin_loan: Option<bool>,
    #[serde(rename = "isFullCash", skip_serializing_if = "Option::is_none")]
    pub is_full_cash: Option<bool>,
}

impl PartialCashPosition {
    pub fn new() -> PartialCashPosition {
        PartialCashPosition {
            amount: None,
            is_margin_loan: None,
            is_full_cash: None,
        }
    }
}

