/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PredefinedDestinationInstructionFinancialInstitution {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "branchCode", skip_serializing_if = "Option::is_none")]
    pub branch_code: Option<String>,
    #[serde(rename = "identifier")]
    pub identifier: String,
    #[serde(rename = "identifierType")]
    pub identifier_type: String,
    #[serde(rename = "clientAccountId")]
    pub client_account_id: String,
}

impl PredefinedDestinationInstructionFinancialInstitution {
    pub fn new(name: String, identifier: String, identifier_type: String, client_account_id: String) -> PredefinedDestinationInstructionFinancialInstitution {
        PredefinedDestinationInstructionFinancialInstitution {
            name,
            branch_code: None,
            identifier,
            identifier_type,
            client_account_id,
        }
    }
}

