/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionnaireType {
    #[serde(rename = "formNo", skip_serializing_if = "Option::is_none")]
    pub form_no: Option<i32>,
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

impl QuestionnaireType {
    pub fn new() -> QuestionnaireType {
        QuestionnaireType {
            form_no: None,
            detail: None,
        }
    }
}

