/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegulatoryInformation {
    #[serde(rename = "regulatoryDetails", skip_serializing_if = "Option::is_none")]
    pub regulatory_details: Option<Vec<models::RegulatoryDetail>>,
    #[serde(rename = "regulatoryDetail", skip_serializing_if = "Option::is_none")]
    pub regulatory_detail: Option<Vec<models::RegulatoryDetail>>,
    #[serde(rename = "selfRegulatedMembership", skip_serializing_if = "Option::is_none")]
    pub self_regulated_membership: Option<Box<models::SelfRegulatedMembershipType>>,
    #[serde(rename = "affiliationDetails", skip_serializing_if = "Option::is_none")]
    pub affiliation_details: Option<Box<models::AffiliationDetailsType>>,
    #[serde(rename = "financialOrgTypes", skip_serializing_if = "Option::is_none")]
    pub financial_org_types: Option<Vec<models::FinancialOrgType>>,
    #[serde(rename = "orgRegulatoryInfo", skip_serializing_if = "Option::is_none")]
    pub org_regulatory_info: Option<Box<models::OrgRegulatoryInfoType>>,
    #[serde(rename = "ausExposureDetails", skip_serializing_if = "Option::is_none")]
    pub aus_exposure_details: Option<Box<models::AusExposureDetailsType>>,
    #[serde(rename = "controllerDetails", skip_serializing_if = "Option::is_none")]
    pub controller_details: Option<Box<models::ControllerDetailsType>>,
    #[serde(rename = "politicalMilitaryDiplomaticDetails", skip_serializing_if = "Option::is_none")]
    pub political_military_diplomatic_details: Option<Box<models::PoliticalMilitaryDiplomaticDetailsType>>,
    #[serde(rename = "isTranslated", skip_serializing_if = "Option::is_none")]
    pub is_translated: Option<bool>,
}

impl RegulatoryInformation {
    pub fn new() -> RegulatoryInformation {
        RegulatoryInformation {
            regulatory_details: None,
            regulatory_detail: None,
            self_regulated_membership: None,
            affiliation_details: None,
            financial_org_types: None,
            org_regulatory_info: None,
            aus_exposure_details: None,
            controller_details: None,
            political_military_diplomatic_details: None,
            is_translated: None,
        }
    }
}

