/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SourceOfWealthType {
    #[serde(rename = "sourceType", skip_serializing_if = "Option::is_none")]
    pub source_type: Option<SourceType>,
    #[serde(rename = "percentage", skip_serializing_if = "Option::is_none")]
    pub percentage: Option<i32>,
    #[serde(rename = "isUsedForFunds", skip_serializing_if = "Option::is_none")]
    pub is_used_for_funds: Option<bool>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl SourceOfWealthType {
    pub fn new() -> SourceOfWealthType {
        SourceOfWealthType {
            source_type: None,
            percentage: None,
            is_used_for_funds: None,
            description: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SourceType {
    #[serde(rename = "SOW-IND-Allowance")]
    IndAllowance,
    #[serde(rename = "SOW-IND-Disability")]
    IndDisability,
    #[serde(rename = "SOW-IND-Income")]
    IndIncome,
    #[serde(rename = "SOW-IND-Inheritance")]
    IndInheritance,
    #[serde(rename = "SOW-IND-Interest")]
    IndInterest,
    #[serde(rename = "SOW-IND-MarketProfit")]
    IndMarketProfit,
    #[serde(rename = "SOW-IND-Other")]
    IndOther,
    #[serde(rename = "SOW-IND-Pension")]
    IndPension,
    #[serde(rename = "SOW-IND-Property")]
    IndProperty,
    #[serde(rename = "SOW-ORG-Business")]
    OrgBusiness,
    #[serde(rename = "SOW-ORG-MarketTradingProfits")]
    OrgMarketTradingProfits,
    #[serde(rename = "SOW-ORG-Other")]
    OrgOther,
    #[serde(rename = "SOW-ORG-OwnerEquity")]
    OrgOwnerEquity,
    #[serde(rename = "SOW-ORG-Property")]
    OrgProperty,
    #[serde(rename = "SOW-ORG-RetainedEarnings")]
    OrgRetainedEarnings,
}

impl Default for SourceType {
    fn default() -> SourceType {
        Self::IndAllowance
    }
}

