/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusResponse {
    #[serde(rename = "requestId", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::ErrorResponse>>,
    #[serde(rename = "hasError", skip_serializing_if = "Option::is_none")]
    pub has_error: Option<bool>,
    #[serde(rename = "errorDescription", skip_serializing_if = "Option::is_none")]
    pub error_description: Option<String>,
    #[serde(rename = "dateSubmitted", skip_serializing_if = "Option::is_none")]
    pub date_submitted: Option<String>,
    #[serde(rename = "isProcessed", skip_serializing_if = "Option::is_none")]
    pub is_processed: Option<bool>,
    #[serde(rename = "fileData", skip_serializing_if = "Option::is_none")]
    pub file_data: Option<Box<models::FileData>>,
    #[serde(rename = "xml", skip_serializing_if = "Option::is_none")]
    pub xml: Option<Box<models::XmlResponse>>,
}

impl StatusResponse {
    pub fn new() -> StatusResponse {
        StatusResponse {
            request_id: None,
            error: None,
            has_error: None,
            error_description: None,
            date_submitted: None,
            is_processed: None,
            file_data: None,
            xml: None,
        }
    }
}

