/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenIntrospectRequest {
    /// The token to introspect.
    #[serde(rename = "token")]
    pub token: String,
    /// An optional hint to help the server identify the token type
    #[serde(rename = "token_type_hint", skip_serializing_if = "Option::is_none")]
    pub token_type_hint: Option<String>,
}

impl TokenIntrospectRequest {
    pub fn new(token: String) -> TokenIntrospectRequest {
        TokenIntrospectRequest {
            token,
            token_type_hint: None,
        }
    }
}

