/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TradingInstrumentDescription {
    #[serde(rename = "securityIdType")]
    pub security_id_type: SecurityIdType,
    #[serde(rename = "securityId")]
    pub security_id: String,
    #[serde(rename = "assetType")]
    pub asset_type: String,
}

impl TradingInstrumentDescription {
    pub fn new(security_id_type: SecurityIdType, security_id: String, asset_type: String) -> TradingInstrumentDescription {
        TradingInstrumentDescription {
            security_id_type,
            security_id,
            asset_type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityIdType {
    #[serde(rename = "CUSIP")]
    Cusip,
    #[serde(rename = "ISIN")]
    Isin,
    #[serde(rename = "CASH")]
    Cash,
}

impl Default for SecurityIdType {
    fn default() -> SecurityIdType {
        Self::Cusip
    }
}

