/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TradingInstrument {
    ConId(String),
    TradingInstrumentDescription(Box<models::TradingInstrumentDescription>),
}

impl Default for TradingInstrument {
    fn default() -> Self {
        Self::ConId(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityIdType {
    #[serde(rename = "CUSIP")]
    Cusip,
    #[serde(rename = "ISIN")]
    Isin,
    #[serde(rename = "CASH")]
    Cash,
}

impl Default for SecurityIdType {
    fn default() -> SecurityIdType {
        Self::Cusip
    }
}

