/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrusteeEntityType {
    #[serde(rename = "legalEntity", skip_serializing_if = "Option::is_none")]
    pub legal_entity: Option<Box<models::LegalEntity>>,
    #[serde(rename = "employee", skip_serializing_if = "Option::is_none")]
    pub employee: Option<Vec<models::Individual>>,
}

impl TrusteeEntityType {
    pub fn new() -> TrusteeEntityType {
        TrusteeEntityType {
            legal_entity: None,
            employee: None,
        }
    }
}

