/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrusteesType {
    #[serde(rename = "individual", skip_serializing_if = "Option::is_none")]
    pub individual: Option<Vec<models::TrusteeIndividual>>,
    #[serde(rename = "entity", skip_serializing_if = "Option::is_none")]
    pub entity: Option<Vec<models::TrusteeEntityType>>,
}

impl TrusteesType {
    pub fn new() -> TrusteesType {
        TrusteesType {
            individual: None,
            entity: None,
        }
    }
}

