/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePropertyProfile {
    #[serde(rename = "referenceAccountId", skip_serializing_if = "Option::is_none")]
    pub reference_account_id: Option<String>,
    #[serde(rename = "propertyProfile", skip_serializing_if = "Option::is_none")]
    pub property_profile: Option<String>,
}

impl UpdatePropertyProfile {
    pub fn new() -> UpdatePropertyProfile {
        UpdatePropertyProfile {
            reference_account_id: None,
            property_profile: None,
        }
    }
}

