/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAccountRepresentatives {
    #[serde(rename = "representativeDetails", skip_serializing_if = "Option::is_none")]
    pub representative_details: Option<Vec<models::RepresentativeDetail>>,
    #[serde(rename = "referenceAccountId", skip_serializing_if = "Option::is_none")]
    pub reference_account_id: Option<String>,
}

impl UpdateAccountRepresentatives {
    pub fn new() -> UpdateAccountRepresentatives {
        UpdateAccountRepresentatives {
            representative_details: None,
            reference_account_id: None,
        }
    }
}

