/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithdrawFundInstructionIraWithdrawalDetail {
    #[serde(rename = "fedIncomeTaxPercentage", skip_serializing_if = "Option::is_none")]
    pub fed_income_tax_percentage: Option<f64>,
    #[serde(rename = "stateIncomeTaxPercentage", skip_serializing_if = "Option::is_none")]
    pub state_income_tax_percentage: Option<f64>,
    #[serde(rename = "stateCd", skip_serializing_if = "Option::is_none")]
    pub state_cd: Option<String>,
    #[serde(rename = "iraWithholdType", skip_serializing_if = "Option::is_none")]
    pub ira_withhold_type: Option<IraWithholdType>,
}

impl WithdrawFundInstructionIraWithdrawalDetail {
    pub fn new() -> WithdrawFundInstructionIraWithdrawalDetail {
        WithdrawFundInstructionIraWithdrawalDetail {
            fed_income_tax_percentage: None,
            state_income_tax_percentage: None,
            state_cd: None,
            ira_withhold_type: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IraWithholdType {
    #[serde(rename = "DIRECT_ROLLOVER")]
    DirectRollover,
    #[serde(rename = "ROTH_DISTRIBUTION")]
    RothDistribution,
    #[serde(rename = "NORMAL")]
    Normal,
    #[serde(rename = "EARLY")]
    Early,
    #[serde(rename = "DEATH")]
    Death,
    #[serde(rename = "EXCESS_CY")]
    ExcessCy,
    #[serde(rename = "EXCESS_PY")]
    ExcessPy,
    #[serde(rename = "EXCESS_SC")]
    ExcessSc,
}

impl Default for IraWithholdType {
    fn default() -> IraWithholdType {
        Self::DirectRollover
    }
}

