/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithholdingStatementType {
    #[serde(rename = "acctId", skip_serializing_if = "Option::is_none")]
    pub acct_id: Option<String>,
    #[serde(rename = "fatcaCompliantType", skip_serializing_if = "Option::is_none")]
    pub fatca_compliant_type: Option<FatcaCompliantType>,
    #[serde(rename = "usBackupWithholding", skip_serializing_if = "Option::is_none")]
    pub us_backup_withholding: Option<bool>,
    #[serde(rename = "treatyCountry", skip_serializing_if = "Option::is_none")]
    pub treaty_country: Option<String>,
    #[serde(rename = "isCorporation", skip_serializing_if = "Option::is_none")]
    pub is_corporation: Option<bool>,
    #[serde(rename = "isFlowThrough", skip_serializing_if = "Option::is_none")]
    pub is_flow_through: Option<bool>,
    #[serde(rename = "effectiveDate", skip_serializing_if = "Option::is_none")]
    pub effective_date: Option<String>,
    #[serde(rename = "dividendRate", skip_serializing_if = "Option::is_none")]
    pub dividend_rate: Option<f32>,
    #[serde(rename = "interestRate", skip_serializing_if = "Option::is_none")]
    pub interest_rate: Option<f32>,
    #[serde(rename = "usOtherRate", skip_serializing_if = "Option::is_none")]
    pub us_other_rate: Option<f32>,
    #[serde(rename = "eciRate", skip_serializing_if = "Option::is_none")]
    pub eci_rate: Option<f32>,
}

impl WithholdingStatementType {
    pub fn new() -> WithholdingStatementType {
        WithholdingStatementType {
            acct_id: None,
            fatca_compliant_type: None,
            us_backup_withholding: None,
            treaty_country: None,
            is_corporation: None,
            is_flow_through: None,
            effective_date: None,
            dividend_rate: None,
            interest_rate: None,
            us_other_rate: None,
            eci_rate: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FatcaCompliantType {
    #[serde(rename = "FATCA_COMPLIANT")]
    FatcaCompliant,
    #[serde(rename = "NON_CONSENTING_US_ACCOUNT")]
    NonConsentingUsAccount,
    #[serde(rename = "NON_COOPERATIVE_ACCOUNT")]
    NonCooperativeAccount,
}

impl Default for FatcaCompliantType {
    fn default() -> FatcaCompliantType {
        Self::FatcaCompliant
    }
}

