/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithdrawableFundsQuery {
    #[serde(rename = "clientInstructionId")]
    pub client_instruction_id: String,
    #[serde(rename = "accountId")]
    pub account_id: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "bankRoutingNumber", skip_serializing_if = "Option::is_none")]
    pub bank_routing_number: Option<String>,
    #[serde(rename = "bankClientAccountNumber", skip_serializing_if = "Option::is_none")]
    pub bank_client_account_number: Option<String>,
}

impl WithdrawableFundsQuery {
    pub fn new(client_instruction_id: String, account_id: String, currency: String) -> WithdrawableFundsQuery {
        WithdrawableFundsQuery {
            client_instruction_id,
            account_id,
            currency,
            bank_routing_number: None,
            bank_client_account_number: None,
        }
    }
}

